# 异步编程总结

python是默认的全同步实现,它的异步都是通过框架实现的,比如gevent,tornado,在3.4之后python加入了async标准包实现了语言级别的异步,但貌似买帐的人不多,也算是历史遗留问题了.

所谓"异步",简单说就是一个任务分成两段,先执行第一段,然后转而执行其他任务,等做好了准备再回过头执行第二段.

比如有一个任务是读取文件进行处理,任务的第一段是向操作系统发出请求,要求读取文件.然后程序执行其他任务,等到操作系统返回文件再接着执行任务的第二段(处理文件).这种不连续的执行就叫做异步.

相应地连续的执行就叫做同步.由于是连续执行不能插入其他任务,所以操作系统从硬盘读取文件的这段时间程序只能干等着.

Js没有这些包袱,所以在异步方案方便确实做得比python好,js中异步处理并发主要手段是:

+ 回调函数与Event对象

+ Promise对象

+ 协程

## 回调函数

这是最原始也是最好理解的手段.所谓回调函数就是把任务的第二段单独写在一个函数里面,等到重新执行这个任务的时候就直接调用这个函数.它的英语名字`callback`,直译过来就是"重新调用".js早期到处都是回调函数.python中的`tornado`框架就是异步回调实现的服务器

在js中这是非常常见的技术,比如读取一个文件:

例子:

```javascript
import fs from "fs"

fs.readFile('./README.md', 'utf-8',function (err, data) {
  if (err) throw err
  console.log(data.slice(0,20))
})
```

结果:

```javascript
# Javascript基础语法

ES
```

上面代码中,readFile函数的第三个参数就是回调函数,也就是任务的第二段.等到操作系统返回了`./README.md`这个文件以后回调函数才会执行.

一个有趣的问题是为什么Node.js约定回调函数的第一个参数必须是错误对象err(如果没有错误，该参数就是null)？原因是执行分成两段,在这两段之间抛出的错误程序无法捕捉,只能当作参数传入第二段.

### 回调的缺点

回调函数本身并没有问题,它的问题出现在多个回调函数嵌套.假定读取A文件之后再读取B文件,代码如下:

```js
fs.readFile(fileA, function (err, data) {
  fs.readFile(fileB, function (err, data) {
    // ...
  })
})
```

如果依次读取多个文件就会出现多重嵌套.代码不是纵向发展而是横向发展,很快就会乱成一团从而无法管理.这种情况就称为"回调函数噩梦"(callback hell)

## 事件驱动

Event对象代表事件的状态,比如事件在其中发生的元素,键盘按键的状态,鼠标的位置,鼠标按钮的状态等.

事件通常与回调函数结合使用,这与tkinter中类似.

我们需要将回调函数绑定到Event对应的方法上,一旦事件被执行,在执行完事件后会构造一个Event对象并将它传入绑定的回调函数中执行.

js在最开始的设计上大量使用了事件驱动.在浏览器上几乎所有交互行为都被定义成了事件,这里有一个[浏览器事件列表](https://developer.mozilla.org/en-US/docs/Web/Events);而node在最开始也沿袭了这个设计,并提供了一个标准库[events](https://nodejs.org/docs/latest/api/events.html)使用来实现事件分发器.浏览器上并没有这个标准库,但可以使用第三方模块[events](https://www.npmjs.com/package/events)来使用`EventEmitter`类(2020年2月26日时为止这个库的api和node11.12.0版本的events库的EventEmitter类一致).

fs也提供了方法`.createReadStream()`构造一个[Readable Streams](https://nodejs.org/docs/latest/api/stream.html#stream_readable_streams),而所有`Streams`对象都是`EventEmitter`类的子类

例子:

```javascript
let file = fs.createReadStream('./README.md', 'utf-8')
file.on("ready",()=>console.log("***file ready***"))
.on("data",(data)=>console.log(data.slice(0,20)))
.on("err",()=>console.log("***发生错误***"))
.on("close",()=>console.log("***file closed***"))
console.log("******")
```

结果:

```javascript
******
***file ready***
# Javascript基础语法

ES
***file closed***
```

### 事件分发器

可以看到事件驱动的方式可以大大丰富代码的扩展性,我们常见的钩子(hooks)就可以理解为一种事件驱动的实现.要实现一个事件分发器也并不复杂,基本就是发布订阅模式的一个应用.

例子:

```javascript
class Emitter{
    constructor(){
        this.channels = new Map()
    }
    emit(event,data=null){
        try{
            if (this.channels.has(event)){
                let funcs = this.channels.get(event)
                funcs.forEach(func=>{
                    if (data){
                        func(data)
                    }else{
                        func()
                    }
                })
            }
        }catch(err){
            this.emit("error",err)
            throw err
        }
    }
    on(event,callback){
        if (this.channels.has(event)){
            this.channels.get(event).push(callback)
        }else{
            this.channels.set(event,[callback])
        }
    }
}

let emitter = new Emitter()

emitter.on('error',(err)=>console.log(`error:${err}`))
emitter.on('data',(data)=>console.log(data))
emitter.on('data',(data)=>{throw new Error("抛出错误")})
emitter.emit('data',{a:1})
```


```javascript
{ a: 1 }
error:Error: 抛出错误



evalmachine.<anonymous>:20

      throw err;

      ^



Error: 抛出错误

    at evalmachine.<anonymous>:5:9

    at evalmachine.<anonymous>:12:13

    at Array.forEach (<anonymous>)

    at Emitter.emit (evalmachine.<anonymous>:10:15)

    at evalmachine.<anonymous>:7:9

    at Script.runInThisContext (vm.js:120:20)

    at Object.runInThisContext (vm.js:311:38)

    at run ([eval]:1054:15)

    at onRunRequest ([eval]:888:18)

    at onMessage ([eval]:848:13)
```

node中已经提供了一个分发器的实现,就在`events.EventEmitter`,而npm中也有一个`events`包可以在浏览器中使用

例子:

```javascript
import {EventEmitter} from 'events'
let emitter2 = new EventEmitter()

emitter2.on('error',(err)=>console.log(`error:${err}`))
emitter2.on('data',(data)=>console.log(data))
emitter2.on('data',(data)=>{throw new Error("抛出错误")})
emitter2.emit('data',{a:1})
```

结果:

```javascript
{ a: 1 }



evalmachine.<anonymous>:7

  throw new Error("抛出错误");

  ^



Error: 抛出错误

    at EventEmitter.<anonymous> (evalmachine.<anonymous>:7:9)

    at EventEmitter.emit (events.js:333:22)

    at evalmachine.<anonymous>:9:10

    at Script.runInThisContext (vm.js:120:20)

    at Object.runInThisContext (vm.js:311:38)

    at run ([eval]:1054:15)

    at onRunRequest ([eval]:888:18)

    at onMessage ([eval]:848:13)

    at process.emit (events.js:321:20)

    at emit (internal/child_process.js:881:12)

```

## Promise

promise翻译成中文就是保证,是异步编程的一种解决方案,比传统的解决方案——回调函数和事件——更合理和更强大.它可以通过链式写法将回调函数穿起来,这样就不再是一层套一层的嵌套写法,回调函数可以像平铺一样的顺序展开写下,这样就更加便于维护.

Promise其实可以理解为规划,如果说回调是面向对象的,那Promise就是面向全局的,它把每种可能都描述在一起,而不是分开来给不同的地方.像上面读取文件的例子.我们可以使用`fs`的Promise接口.

例子:

```javascript
fs.promises.readFile('./README.md', 'utf-8')
    .then(data=>console.log(data.slice(0,20)))
    .catch(error=>console.error(error))
```

结果:

```javascript
# Javascript基础语法

ES
```

## 协程

类比Python中的协程,js中的协程实现是基于Promise的,在vm中已经集成了全局的事件循环,我们可以用`async function`的方式定义协程函数,调用它可以创建一个协程,并将其加入到事件循环中监听调度.而一些针对任务的精细化处理则由`Promise`对象提供接口.

和python中一样协程语法的最大贡献实际上是在与编程人员的交互层,毕竟这套语法极大地降低了编程人员的心智负担.但问题也一样--协程语法是侵入式的,这也就意味着使用写成语法的模块一整个调用链路都得是协程语法.

### 常用的支持promise的第三方异步库

+ http客户端<https://github.com/axios/axios>
+ http服务端<https://github.com/koajs/koa>
+ 文件系统<https://www.npmjs.com/package/fs-extra>
+ orm<https://github.com/sequelize/sequelize>

